name: Telekinetic_Reality
main: com.osreboot.tr.main.Main
version: ${project.version}
description: Telekinetic Reality by Os_Reboot updated by TrollyLoki
authors: [os_reboot, TrollyLoki]
softdepend: [WorldGuard]
api-version: 1.16
commands:
   syntax:
      description: Opens syntax tree.
   tr:
      description: Gets plugin version.
   trlog:
      description: Gets latest changelog.